### ISSUE TITLE
Implement about page

### ISSUE THREAD

**Issue by jberns** [codefordenver/energy-assistance-dashboard#66]
Waiting on #62

**Comment by anotherpatrickcollins** [comment]
_Content_

Energy Outreach Colorado was established in 1989 and we believe everyone deserves affordable access to the vital resources that power their homes. When everyone can afford and maintain their home, then they can focus on living, rather than merely surviving.

We lead a network of industry, state and local partners to Support, Stabilize and Sustain Coloradans to afford their energy needs.

**Comment by anotherpatrickcollins** [comment]
_Content_

Code for Denver is a group of volunteer technologists who build software to help nonprofits and local government better serve their community.
